dist: trusty

language:
  - python

python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6

cache:
  pip: true

# command to install dependencies
install:
  - pip install coverage
  - pip install codecov

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

# command to run tests
script: coverage run tests/runtests.py

after_success:
  - codecov

matrix:
  fast_finish: true
